/* AZ-900 Drill Room — all study content lives in this file.
   Everything is derived from the AZ-900 content reference PDF (scoped to the
   official Microsoft skills outline, updated 14 Jan 2026). If anything here
   disagrees with Microsoft Learn, Learn is correct.

   To add content, append objects to the arrays below. Fields:
     trapCards / fullCards : { c: front, a: answer, w: one-line why, d: domain 1|2|3 }
     examBank / scenarios  : { q, opts: [4 strings], c: index of correct, w: why, d }
     matchPairs            : { c: cue, a: answer, d }
*/

const AZ_DATA = {

trapCards: [
// ---- Domain 1 · cloud concepts ----
{c:"recover from failure / fault tolerance", a:"Reliability", w:"The ability to recover from failures and continue to function.", d:1},
{c:"consistent performance under load AND a forecastable bill", a:"Predictability", w:"Two flavours the exam separates: performance predictability and cost predictability.", d:1},
{c:"scale automatically out and in as demand rises and falls", a:"Elasticity", w:"Scalability is the capability; elasticity is doing it dynamically.", d:1},
{c:"move to a bigger machine — more CPU / RAM", a:"Vertical scaling (scale up / down)", w:"One machine, bigger spec.", d:1},
{c:"add or remove instances of the same machine", a:"Horizontal scaling (scale out / in)", w:"Generally gives better resilience than scaling up.", d:1},
{c:"buying servers up front", a:"CapEx (capital expenditure)", w:"The consumption model turns this into OpEx.", d:1},
{c:"ongoing metered running cost", a:"OpEx (operational expenditure)", w:"Pay-as-you-go spend instead of upfront purchase.", d:1},
{c:"pay only for what you actually use, no upfront purchase", a:"Consumption-based model", w:"No wasted spend on idle hardware; no over-provisioning for peaks.", d:1},
{c:"commit for 1 or 3 years in exchange for a large discount", a:"Reserved instances / capacity", w:"For steady, predictable workloads.", d:1},
{c:"heavily discounted spare capacity Azure can reclaim at any time", a:"Spot pricing", w:"Interruptible work only.", d:1},
{c:"sensitive data must stay on-premises, but bursts to public cloud for peaks", a:"Hybrid cloud", w:"Combines public and private so workloads can move between them.", d:1},
{c:"in SaaS, what is still ALWAYS yours to manage?", a:"Your data, identities/accounts, and access", w:"The top layer never transfers to Microsoft — plus your endpoint devices.", d:1},
{c:"what does Microsoft ALWAYS own, in every service model?", a:"The physical layer", w:"Datacentres, physical hosts, and the physical network.", d:1},
{c:"you supply only code or logic; the platform provisions, scales and tears down", a:"Serverless", w:"Azure Functions, Logic Apps. It doesn't mean no servers — you just don't manage them.", d:1},
{c:"'wants to deploy a web app and never touch a server'", a:"PaaS (App Service)", w:"You manage only your app and data.", d:1},
{c:"'needs full control of the operating system'", a:"IaaS (a virtual machine)", w:"You own everything from the OS up, including patching.", d:1},
{c:"'just needs working email / CRM, ready to use'", a:"SaaS", w:"Microsoft manages the whole application; you manage data and user access.", d:1},

// ---- Domain 2 · architecture & services ----
{c:"survive ONE datacentre failing", a:"Availability zones (storage: ZRS)", w:"3+ physically separate locations in a region, each with independent power, cooling, networking.", d:2},
{c:"VM resilience INSIDE a single datacentre", a:"Availability set", w:"Fault domains (racks/power) + update domains (staggered reboots). Won't survive losing the whole building.", d:2},
{c:"survive a WHOLE REGION failing", a:"GRS / GZRS", w:"An asynchronous copy in the paired region.", d:2},
{c:"must be able to READ the backup copy in the other region", a:"RA-GRS / RA-GZRS", w:"The RA- variants add read access to the secondary.", d:2},
{c:"pinned to one specific zone vs spread across zones automatically", a:"Zonal vs zone-redundant", w:"You pick the zone, or the service replicates across zones for you.", d:2},
{c:"~300 miles apart, platform updates roll out one at a time", a:"Region pairs", w:"Caveats: not every region has a pair, and pairing alone does NOT give you failover/DR — you design that.", d:2},
{c:"physically isolated Azure for legal / compliance boundaries", a:"Sovereign regions", w:"Azure Government (US), Azure operated by 21Vianet (China).", d:2},
{c:"a resource belongs to exactly ___ resource group(s)", a:"One", w:"And deleting the group deletes everything in it.", d:2},
{c:"billing boundary + access boundary + resource limits/quotas", a:"Subscription", w:"Orgs use multiple to split prod/dev, billing, or teams.", d:2},
{c:"apply RBAC / Policy once across MANY subscriptions", a:"Management group", w:"Nestable containers above subscriptions; settings inherit downward.", d:2},
{c:"the hierarchy, top to bottom", a:"Management group → subscription → resource group → resource", w:"Policy and role assignments inherit downward, never up.", d:2},
{c:"can resource groups be nested? can they hold resources from other regions?", a:"No nesting; yes, any region", w:"The group's own region only stores its metadata.", d:2},
{c:"identical VMs that automatically scale in count behind a load balancer", a:"VM Scale Sets", w:"How IaaS VMs achieve elasticity.", d:2},
{c:"virtualised Windows desktops delivered from Azure", a:"Azure Virtual Desktop", w:"Central management, optional multi-session hosts.", d:2},
{c:"reuse Windows / SQL licences you already own", a:"Azure Hybrid Benefit", w:"A VM pricing lever, alongside reserved and spot.", d:2},
{c:"VM letters: B / D / F", a:"Burstable · Default (general purpose) · Fast CPU", w:"Match the family to the workload shape, not size names.", d:2},
{c:"VM letters: E-M / L / N / H", a:"Extra-Massive memory · Lots of disk · GPU (iNference) · HPC", w:"E/M memory, L storage throughput, N graphics/AI, H simulation.", d:2},
{c:"SAP HANA or a huge in-memory database", a:"M-series (memory optimised)", w:"M = ultra-high memory.", d:2},
{c:"CPU-bound batch processing, app servers, gaming", a:"F-series (compute optimised)", w:"High CPU-to-memory ratio.", d:2},
{c:"big data with high local disk throughput and IOPS", a:"L-series (storage optimised)", w:"Data warehousing, large transactional/NoSQL DBs.", d:2},
{c:"AI / ML training, rendering, visualisation", a:"N-series (GPU)", w:"Graphics and parallel compute.", d:2},
{c:"shares the host's OS kernel, starts in seconds", a:"A container", w:"A VM virtualises the hardware; a container virtualises the OS.", d:2},
{c:"immutable template vs running instance", a:"Image vs container", w:"'Class vs object': one image, many identical containers. Built from a Dockerfile.", d:2},
{c:"where container images are stored and shared on Azure", a:"Azure Container Registry (ACR)", w:"The registry service.", d:2},
{c:"one or a few simple containers, no orchestration, pay per second", a:"Azure Container Instances (ACI)", w:"Serverless, quick, for simple or burst tasks.", d:2},
{c:"MANY containers needing scheduling, self-healing, rolling updates", a:"Azure Kubernetes Service (AKS)", w:"Azure runs the control plane; you manage the worker nodes.", d:2},
{c:"serverless microservices with autoscaling, without managing Kubernetes", a:"Azure Container Apps", w:"The middle ground between ACI and AKS.", d:2},
{c:"what causes a Function to run — and how many can it have?", a:"A trigger — exactly one", w:"The trigger also carries the input data.", d:2},
{c:"declarative data in/out for a Function, no connection code", a:"Bindings", w:"Optional, and a function can have several (input and output).", d:2},
{c:"short delay when a Consumption-plan function wakes after idle", a:"Cold start", w:"Need consistent low latency → Premium / Flex Consumption (pre-warmed).", d:2},
{c:"stateful or long-running workflows in Functions", a:"Durable Functions", w:"Plain functions are stateless and short-lived (~10 min max on serverless).", d:2},
{c:"what every Function App must have associated with it", a:"A storage account", w:"Used for triggers, logging, and scaling state.", d:2},
{c:"private, dedicated, does NOT use the public internet", a:"ExpressRoute", w:"Via a connectivity provider — faster, more consistent, more secure, higher cost.", d:2},
{c:"encrypted connection OVER the internet, lower cost", a:"VPN Gateway", w:"Performance depends on the internet.", d:2},
{c:"connect a whole network vs a single client device", a:"Site-to-site vs point-to-site VPN", w:"S2S = on-prem network to Azure; P2S = one laptop.", d:2},
{c:"connect two VNets so traffic stays on Microsoft's backbone", a:"VNet peering", w:"Within a region, or global across regions.", d:2},
{c:"give a PaaS service a private IP inside your VNet", a:"Private endpoint", w:"Traffic stays off the public internet; a public endpoint is internet-reachable.", d:2},
{c:"unstructured data: images, video, backups, logs", a:"Blob Storage", w:"Massively scalable object storage over HTTP/HTTPS.", d:2},
{c:"drop-in replacement for an on-prem file server (SMB / NFS)", a:"Azure Files", w:"Mountable from cloud and on-prem simultaneously.", d:2},
{c:"large numbers of messages to decouple app components", a:"Queue Storage", w:"Smooths out workload spikes.", d:2},
{c:"NoSQL key/value store, cheap, structured but non-relational", a:"Table Storage", w:"For large amounts of structured non-relational data.", d:2},
{c:"tiers: frequent / min 30 days / min 90 days / offline", a:"Hot / Cool / Cold / Archive", w:"Archive must be rehydrated (hours) before reading and has the priciest retrieval.", d:2},
{c:"3 copies in ONE datacentre vs copies ACROSS zones", a:"LRS vs ZRS", w:"LRS survives disk/server faults only; ZRS survives a zone loss.", d:2},
{c:"GUI desktop app vs command-line bulk copy for storage", a:"Storage Explorer vs AzCopy", w:"Browse-and-manage vs fast scripted transfer.", d:2},
{c:"keep an on-prem Windows file server synced, caching hot data locally", a:"Azure File Sync", w:"Extends Azure Files to on-prem servers.", d:2},
{c:"physical appliance shipped to you for very large offline transfers", a:"Azure Data Box", w:"When the network would be too slow. Azure Migrate is the assess-and-migrate hub.", d:2},
{c:"proving WHO you are vs what you're ALLOWED to do", a:"Authentication (Entra ID) vs authorization (RBAC)", w:"Conditional Access sits between: it decides whether/how sign-in proceeds.", d:2},
{c:"evaluate sign-in signals, then allow / block / require MFA", a:"Conditional Access", w:"Signals: user, group, location/IP, device state, real-time risk.", d:2},
{c:"one sign-in grants access to many applications", a:"SSO (single sign-on)", w:"Reduces password fatigue and risk.", d:2},
{c:"something you know + have + are", a:"MFA factors", w:"Two or more categories: password, phone/token, biometric.", d:2},
{c:"sign in with an authenticator app, FIDO2 key, or Windows Hello", a:"Passwordless authentication", w:"No password at all.", d:2},
{c:"partners use their OWN credentials vs identity for your customer app", a:"B2B vs B2C", w:"External identities: guests vs consumers.", d:2},
{c:"domain join, Group Policy, LDAP, Kerberos — without running domain controllers", a:"Microsoft Entra Domain Services", w:"Managed traditional domain capabilities for legacy apps.", d:2},
{c:"verify explicitly · least privilege · assume breach", a:"Zero Trust", w:"Trust nothing by default, even inside the perimeter.", d:2},
{c:"layered defences: physical → identity → … → data at the centre", a:"Defense in depth", w:"No single failure is catastrophic; data is the protected core.", d:2},
{c:"secure score, recommendations, and workload threat protection — across clouds", a:"Microsoft Defender for Cloud", w:"Continuously assesses posture on Azure, on-prem, and other clouds.", d:2},

// ---- Domain 3 · management & governance ----
{c:"ESTIMATE the cost of a build you haven't deployed yet", a:"Pricing Calculator", w:"Compare configurations before you commit.", d:3},
{c:"compare running on-premises vs in Azure", a:"TCO Calculator", w:"Total Cost of Ownership — the migration business case tool.", d:3},
{c:"track ACTUAL spend, set budgets, fire cost alerts", a:"Microsoft Cost Management", w:"The 'what am I really spending' tool.", d:3},
{c:"which traffic direction is usually billed?", a:"Egress", w:"Data leaving Azure or crossing regions is billed; ingress is generally free.", d:3},
{c:"name/value metadata used to organise resources and group cost reports", a:"Tags", w:"E.g. Environment=Prod, CostCentre=Finance — can also drive policy.", d:3},
{c:"WHO can do WHAT, at a scope", a:"Azure RBAC", w:"Roles assigned at MG / subscription / RG / resource. Additive, inherits down, least privilege.", d:3},
{c:"WHAT configuration is permitted — audit or deny creation", a:"Azure Policy", w:"E.g. only allowed regions, required tags, approved VM sizes. Grouped policies = an initiative.", d:3},
{c:"stop THIS resource being deleted, even by someone with rights", a:"Resource lock", w:"CanNotDelete = modify but not delete; ReadOnly = no changes at all. Inherits downward.", d:3},
{c:"discover, catalogue, and classify data across your whole estate", a:"Microsoft Purview", w:"Unified data governance and compliance.", d:3},
{c:"personalised recommendations across five pillars", a:"Azure Advisor", w:"Cost, security, reliability, operational excellence, performance.", d:3},
{c:"is AZURE ITSELF having problems that affect me?", a:"Azure Service Health", w:"Outages, planned maintenance, advisories for YOUR regions/services. Per-resource = Resource Health.", d:3},
{c:"collect and QUERY my own metrics and logs", a:"Azure Monitor", w:"Log Analytics (KQL queries), alerts, and Application Insights for app performance.", d:3},
{c:"manage on-prem servers and other clouds as if they were Azure resources", a:"Azure Arc", w:"Applies Policy and RBAC consistently outside Azure.", d:3},
{c:"declarative files describing the desired end-state", a:"Infrastructure as Code", w:"ARM templates (JSON) or Bicep (compiles to ARM) — repeatable, version-controlled.", d:3},
{c:"the layer that receives and executes EVERY create/update/delete request", a:"Azure Resource Manager (ARM)", w:"Portal, CLI, PowerShell and SDKs all go through it.", d:3},
{c:"browser-based shell, already authenticated, no install", a:"Azure Cloud Shell", w:"Offers Azure CLI (az, Bash-style) and Azure PowerShell — pick by scripting preference.", d:3},
{c:"a score of 700/1000 means…", a:"A scaled score — NOT 70% correct", w:"Confirmed by Microsoft; question count, timing and cost vary — verify at booking.", d:3}
],

fullCards: [
// ---- Domain 1 · cloud concepts (25–30%) ----
{c:"What is cloud computing?", a:"Renting IT resources on demand over the internet", w:"Compute, storage, networking, databases, analytics, AI from a provider instead of buying your own. Capacity in minutes, released when done.", d:1},
{c:"What is the shared responsibility model?", a:"Security and management duties split between you and Microsoft", w:"The split moves with the service type (IaaS → PaaS → SaaS).", d:1},
{c:"In the shared responsibility model, what never moves?", a:"Microsoft: the physical layer. You: data, identities, access", w:"Datacentres, hosts and physical network are always Microsoft's; your data, accounts and endpoint devices are always yours.", d:1},
{c:"What is the consumption-based (pay-as-you-go) model?", a:"Pay only for what you actually use, with no upfront purchase", w:"No wasted spend on idle hardware; no over-provisioning for peak demand.", d:1},
{c:"What is CapEx?", a:"Capital expenditure — buying servers up front", w:"The cloud turns this into OpEx.", d:1},
{c:"What is OpEx?", a:"Operational expenditure — ongoing metered running cost", w:"What the consumption model produces.", d:1},
{c:"Name the three cloud pricing models.", a:"Pay-as-you-go, reserved, spot", w:"PAYG = full flexibility, highest unit price. Reserved = 1/3-year commitment discount for steady workloads. Spot = cheap reclaimable capacity for interruptible work.", d:1},
{c:"What does 'serverless' actually mean?", a:"You supply only code or logic; the platform provisions, scales, and tears down", w:"You pay per execution, not for always-on servers. Servers exist — you just don't manage them.", d:1},
{c:"Name two serverless services.", a:"Azure Functions and Logic Apps", w:"Event-driven code, and workflows.", d:1},
{c:"What is the public cloud?", a:"The provider's shared, multi-tenant infrastructure accessed over the internet", w:"No capital cost, near-infinite scale, less low-level control. Best for variable demand, startups, web apps.", d:1},
{c:"What is the private cloud?", a:"Cloud infrastructure dedicated to a single organisation", w:"On-prem or hosted. Maximum control/isolation for strict compliance — but you bear cost and maintenance, and scale is limited by your hardware.", d:1},
{c:"What is the hybrid cloud?", a:"Public + private, connected so workloads and data can move between them", w:"Keep sensitive systems private while bursting to public for scale, or migrate gradually. Most enterprises land here.", d:1},
{c:"What is high availability?", a:"Designing so the service keeps running despite failures", w:"Expressed as an availability SLA; achieved with redundancy across hardware, zones and regions.", d:1},
{c:"What is an availability SLA?", a:"A percentage of uptime the provider commits to", w:"The way high availability is expressed.", d:1},
{c:"What is scalability?", a:"The ability to add resources to meet demand", w:"Vertical or horizontal.", d:1},
{c:"Vertical scaling is…", a:"Scale up/down — a bigger or smaller machine", w:"More (or less) CPU/RAM on one machine.", d:1},
{c:"Horizontal scaling is…", a:"Scale out/in — add or remove identical instances", w:"Generally gives better resilience than vertical.", d:1},
{c:"What is elasticity?", a:"Scaling automatically out and in as demand rises and falls", w:"Scalability is the capability; elasticity is doing it dynamically — never short at peak, never paying for idle.", d:1},
{c:"What is reliability?", a:"The system's ability to recover from failures and continue to function", w:"Fault tolerance and disaster recovery; the global footprint of regions/zones makes it practical.", d:1},
{c:"What are the two flavours of predictability?", a:"Performance predictability and cost predictability", w:"Autoscaling/load balancing keep responses consistent; cost tools, forecasting and tags keep spend anticipated.", d:1},
{c:"How does the cloud help security and governance?", a:"Provider patches/hardens infrastructure; templates and policies enforce your standards automatically", w:"Governance tools apply corporate and regulatory rules at scale.", d:1},
{c:"'Management OF the cloud' means…", a:"Autoscale on demand, deploy from templates, monitor and alert automatically", w:"The cloud managing resources for you.", d:1},
{c:"'Management IN the cloud' means…", a:"How you administer: portal, CLI, PowerShell, or APIs", w:"Your choice of tooling.", d:1},
{c:"In IaaS, what do you manage vs Microsoft?", a:"You: OS, patching, runtime, apps, data, network config. Microsoft: hosts, datacentre, virtualisation", w:"Most control of the three service types.", d:1},
{c:"In PaaS, what do you manage?", a:"Only your apps and data", w:"Microsoft handles OS, runtime, scaling, hosting, hardware. The application layer is shared.", d:1},
{c:"In SaaS, what do you manage?", a:"Your data and user access", w:"Microsoft runs the entire application.", d:1},
{c:"IaaS — best for, and an Azure example?", a:"Lift-and-shift, legacy or specialised software. Azure VMs, VNets", w:"Choose it when you need the most control.", d:1},
{c:"PaaS — best for, and an Azure example?", a:"Building/deploying apps without server admin. App Service, Azure SQL Database", w:"You never touch a server.", d:1},
{c:"SaaS — Azure/Microsoft examples?", a:"Microsoft 365, Dynamics 365", w:"Ready-to-use software, no build.", d:1},
{c:"In which service model is the application layer 'shared'?", a:"PaaS", w:"You and Microsoft share responsibility for applications in PaaS.", d:1},
{c:"In which models are YOU responsible for patching the OS?", a:"On-premises and IaaS", w:"From PaaS upward, Microsoft owns the OS/runtime.", d:1},
{c:"List the exam's benefit categories.", a:"High availability, scalability, elasticity, reliability, predictability, security & governance, manageability", w:"The 'describe the benefits' objective in Domain 1.", d:1},
{c:"What are the AZ-900 domain weightings?", a:"Concepts 25–30% · Architecture & services 35–40% · Management & governance 30–35%", w:"Architecture & services is the biggest domain.", d:1},

// ---- Domain 2 · architecture & services (35–40%) ----
{c:"What is a region?", a:"A geographic area of one or more low-latency-networked datacentres", w:"You choose one at deploy time; service availability and price can vary by region.", d:2},
{c:"What is a region pair?", a:"Two regions in the same geography, ~300 miles apart, paired for disaster recovery", w:"Platform updates roll out to one region of the pair at a time; one is prioritised for recovery in a geography-wide outage.", d:2},
{c:"What are the region-pair caveats Microsoft now stresses?", a:"Not every region has a pair, and pairing alone gives you no HA/failover/DR", w:"Many newer regions are non-paired and rely on availability zones; you design DR yourself (e.g. geo-redundant storage).", d:2},
{c:"What are sovereign regions?", a:"Physically isolated Azure instances for compliance/legal boundaries", w:"Azure Government (US) and Azure operated by 21Vianet (China) — separate from the public global cloud.", d:2},
{c:"What are availability zones?", a:"Three or more physically separate locations within one region", w:"Each has independent power, cooling and networking; protects against a single datacentre failing.", d:2},
{c:"Zonal vs zone-redundant?", a:"You pin the resource to a zone, vs the service spreads copies across zones automatically", w:"Two ways to use zones.", d:2},
{c:"What is a resource?", a:"Any individual manageable Azure item", w:"A VM, a database, a storage account, a public IP.", d:2},
{c:"What is a resource group?", a:"A logical container holding related resources", w:"Each resource belongs to exactly one group; deleting the group deletes everything in it.", d:2},
{c:"Resource group region and nesting rules?", a:"Its region stores only metadata; contents can be from any region; groups cannot be nested", w:"Three classic trap facts in one.", d:2},
{c:"What is a subscription?", a:"A logical unit of billing and a boundary for access and limits/quotas", w:"Where the containment, billing and identity chains meet.", d:2},
{c:"Why do organisations run multiple subscriptions?", a:"Separate environments, separate billing/cost ownership, or to work around per-subscription limits", w:"Prod vs dev, per-team billing, quotas.", d:2},
{c:"What are management groups?", a:"Nestable containers above subscriptions", w:"Apply RBAC and Policy once and it inherits to every subscription beneath; several nesting levels under a single root.", d:2},
{c:"State the resource hierarchy, top to bottom.", a:"Management group → subscription → resource group → resource", w:"Policy and role assignments inherit downward, never up.", d:2},
{c:"How many Entra tenants does a subscription trust?", a:"One", w:"The identity chain: subscription → its Entra tenant. The billing chain runs up to the account.", d:2},
{c:"What is a virtual machine?", a:"A software-defined computer on Microsoft's physical servers, with a full OS you control", w:"You install software, configure networking, and are responsible for patching from the OS up.", d:2},
{c:"What does a VM need to run?", a:"A size, an OS disk (+ optional data disks), a VNet + NIC, and a public IP only if internet-reachable", w:"Built from a Marketplace or custom image. Managed disks: Standard HDD/SSD, Premium SSD, Ultra.", d:2},
{c:"What are VM Scale Sets?", a:"A managed group of identical VMs that auto-scales instance count behind a load balancer", w:"On demand or schedule — how VMs achieve elasticity.", d:2},
{c:"What are availability sets?", a:"VM resilience within one datacentre via fault domains and update domains", w:"Separate racks/power/network; staggered patching/reboots. Not whole-datacentre loss — that's zones.", d:2},
{c:"What is Azure Virtual Desktop?", a:"Virtualised Windows desktops and apps delivered from Azure", w:"Connect from anywhere; central management; optional multi-session hosts.", d:2},
{c:"Name the four VM pricing levers.", a:"Pay-as-you-go, reserved instances, spot, Azure Hybrid Benefit", w:"AHB reuses existing Windows/SQL licences.", d:2},
{c:"Name the six VM families.", a:"General purpose, compute optimised, memory optimised, storage optimised, GPU, HPC", w:"Match the workload to the family; series letters set the specifics.", d:2},
{c:"General purpose VMs (A, B, D) suit…", a:"Web servers, small/medium databases, dev & test", w:"Balanced CPU-to-memory; B = burstable/economical, D = default.", d:2},
{c:"Compute optimised VMs (F) suit…", a:"CPU-bound work: batch processing, app servers, network appliances, gaming", w:"High CPU-to-memory ratio.", d:2},
{c:"Memory optimised VMs (E, M) suit…", a:"Large in-memory databases, caches, analytics, SAP HANA", w:"M = ultra-high memory.", d:2},
{c:"Storage optimised VMs (L) suit…", a:"Big data, data warehousing, large transactional/NoSQL databases", w:"High local disk throughput and IOPS.", d:2},
{c:"GPU VMs (N: ND/NC/NV) suit…", a:"AI/ML training and inference, rendering, visualisation", w:"Graphics and parallel compute.", d:2},
{c:"HPC VMs (H: HB/HX) suit…", a:"Simulation, modelling, fluid dynamics, scientific/financial compute", w:"Fastest CPUs plus fast networking.", d:2},
{c:"What is a container?", a:"A lightweight, isolated package of an app plus everything it needs to run", w:"Shares the host OS kernel instead of carrying a guest OS — smaller, starts in seconds, packs densely.", d:2},
{c:"VM vs container, in one line?", a:"A VM virtualises the hardware; a container virtualises the operating system", w:"VMs = stronger isolation and any OS; containers = portability, speed, density.", d:2},
{c:"Dockerfile, image, container, registry — define the chain.", a:"Dockerfile (recipe) builds an image (immutable template); a running instance is a container; images live in a registry", w:"On Azure the registry is ACR. Image vs container = class vs object.", d:2},
{c:"Why do containers matter?", a:"Build once, run anywhere", w:"The same image runs identically on a laptop, on-prem or Azure — no 'works on my machine', fast consistent scaling.", d:2},
{c:"What is Azure Container Instances (ACI)?", a:"Run a single container or small group quickly, no orchestration, no servers", w:"Serverless, pay per second — simple, short, or burst tasks.", d:2},
{c:"What is Azure Kubernetes Service (AKS)?", a:"Managed Kubernetes orchestrating many containers across a cluster", w:"Automatic scheduling, scaling, self-healing, rolling updates. Azure runs the control plane; you manage worker nodes.", d:2},
{c:"What is Azure Container Apps?", a:"A serverless container platform for microservices and event-driven apps", w:"Built-in autoscaling without managing Kubernetes — the middle ground between ACI and AKS.", d:2},
{c:"What are Azure Functions?", a:"Small pieces of event-driven code, run without provisioning servers", w:"Azure handles infrastructure and scaling; on the serverless plan you pay only for run time. Short, stateless, single-purpose.", d:2},
{c:"What is a Function trigger?", a:"What causes the function to run — and it carries the input data", w:"Every function has exactly one.", d:2},
{c:"Name common Function triggers.", a:"HTTP, Timer, Queue/Service Bus, Blob, Event Grid/Event Hubs, Cosmos DB", w:"API/webhook, schedules, messages, file uploads, events, data changes.", d:2},
{c:"What are Function bindings?", a:"Declarative connections to other services, no plumbing code", w:"Input bindings bring data in; output bindings send it out. Optional, and several are allowed.", d:2},
{c:"What are the Function design constraints?", a:"Stateless and short-lived by design (~10 min max on the serverless plan)", w:"For stateful or long workflows, use Durable Functions.", d:2},
{c:"What must every Function App have associated with it?", a:"An Azure Storage account", w:"For managing triggers, logging, and scaling state.", d:2},
{c:"Name the Function hosting plans.", a:"Consumption, Premium / Flex Consumption, Dedicated (App Service plan)", w:"Consumption: scale to zero, pay per execution, cold starts. Premium/Flex: pre-warmed, VNet, longer runtimes. Dedicated: always-on VMs, predictable cost.", d:2},
{c:"Order the compute options from most control to most convenience.", a:"VM → containers → App Service → Functions", w:"More control means more to manage; less to manage means more convenience.", d:2},
{c:"What is a virtual network (VNet)?", a:"Your private, isolated network within Azure", w:"Segmented into subnets; you control the address space.", d:2},
{c:"What is VNet peering?", a:"Connecting two VNets so traffic routes privately over Microsoft's backbone", w:"Within a region, or global across regions.", d:2},
{c:"What is Azure DNS?", a:"Host your DNS domains in Azure and resolve names on Microsoft's infrastructure", w:"Integrates with other Azure services.", d:2},
{c:"What is Azure VPN Gateway?", a:"An encrypted tunnel between your network and Azure over the public internet", w:"Site-to-site connects whole networks; point-to-site connects individual devices. Cheaper, but internet-dependent.", d:2},
{c:"What is ExpressRoute?", a:"A private, dedicated connection into Azure through a connectivity provider", w:"Never touches the public internet — more reliable, faster, more consistent, more secure, at higher cost.", d:2},
{c:"Public vs private endpoint?", a:"Internet-reachable public IP vs a private IP inside your VNet", w:"Private endpoints keep traffic on the private network and off the internet.", d:2},
{c:"What is Blob Storage?", a:"Massively scalable object storage for unstructured data", w:"Images, video, backups, logs, documents, big data — over HTTP/HTTPS.", d:2},
{c:"What is Azure Files?", a:"Fully managed cloud file shares over SMB or NFS", w:"Mountable from cloud and on-prem simultaneously — a drop-in file-server replacement.", d:2},
{c:"What is Disk Storage?", a:"Block-level disks attached to VMs", w:"OS and data disks, in HDD/SSD performance tiers.", d:2},
{c:"What is Queue Storage?", a:"Stores large numbers of messages to decouple application components", w:"Smooths out workload spikes.", d:2},
{c:"What is Table Storage?", a:"A NoSQL key/value store for structured, non-relational data", w:"Large amounts, cheaply, at scale.", d:2},
{c:"Describe the Hot access tier.", a:"Frequent access — highest storage price, lowest access price", w:"The default for active data.", d:2},
{c:"Describe the Cool access tier.", a:"Infrequent access, minimum 30 days", w:"Lower storage cost, higher access cost than Hot.", d:2},
{c:"Describe the Cold access tier.", a:"Rarely accessed, minimum 90 days", w:"Cheaper still than Cool, online.", d:2},
{c:"Describe the Archive access tier.", a:"Offline — cheapest storage, most expensive retrieval", w:"Data must be rehydrated (can take hours) before you can read it.", d:2},
{c:"What is LRS?", a:"Locally-redundant: 3 copies in one datacentre", w:"Cheapest; survives disk/server faults only.", d:2},
{c:"What is ZRS?", a:"Zone-redundant: copies across availability zones in one region", w:"Survives a datacentre/zone loss.", d:2},
{c:"What is GRS?", a:"Geo-redundant: LRS locally plus an asynchronous copy in the paired region", w:"Survives a whole-region outage.", d:2},
{c:"What is GZRS?", a:"ZRS locally plus the paired region", w:"The most durable option.", d:2},
{c:"What do the RA- variants add?", a:"Read access to the secondary region's copy", w:"RA-GRS / RA-GZRS.", d:2},
{c:"What is a storage account?", a:"The top-level container for blobs, files, queues and tables under one unique namespace", w:"Where you pick performance (Standard/Premium) and redundancy.", d:2},
{c:"What is AzCopy?", a:"A command-line tool for fast bulk copy to/from storage", w:"Scriptable transfers.", d:2},
{c:"What is Azure Storage Explorer?", a:"A GUI desktop app to browse and manage storage", w:"The point-and-click option.", d:2},
{c:"What is Azure File Sync?", a:"Keeps on-prem Windows file servers in sync with Azure Files", w:"Caches hot data locally.", d:2},
{c:"What is Azure Migrate?", a:"A central hub to discover, assess, and migrate to Azure", w:"Servers, databases, web apps, and data.", d:2},
{c:"What is Azure Data Box?", a:"A ruggedised physical appliance Microsoft ships to you", w:"For moving very large datasets offline when the network would be too slow.", d:2},
{c:"What is Microsoft Entra ID?", a:"Microsoft's cloud identity and access management service (formerly Azure AD)", w:"Authenticates users and apps; controls access to Azure, Microsoft 365, and thousands of SaaS apps.", d:2},
{c:"What is Microsoft Entra Domain Services?", a:"Managed traditional domain capabilities without managing domain controllers", w:"Domain join, Group Policy, LDAP, Kerberos/NTLM — for lifting legacy apps that need a domain.", d:2},
{c:"What is SSO?", a:"One sign-in grants access to many applications", w:"Reduces password fatigue and risk.", d:2},
{c:"What does MFA require?", a:"Two or more of: something you know, have, or are", w:"Password; phone/token; biometric.", d:2},
{c:"Name the passwordless methods.", a:"Authenticator app, FIDO2 security key, Windows Hello", w:"Sign in without a password at all.", d:2},
{c:"B2B vs B2C?", a:"B2B invites partners/guests with their own credentials; B2C manages identity for customer-facing apps", w:"The two external-identity flavours.", d:2},
{c:"What is Conditional Access?", a:"Policies that evaluate sign-in signals, then allow, block, or require extra proof", w:"Signals: user, group, location/IP, device state, real-time risk. Classic example: require MFA outside the corporate network.", d:2},
{c:"What is Azure RBAC?", a:"Grant access by assigning roles at a scope", w:"Built-in (Reader/Contributor/Owner) or custom; to users, groups, apps; at MG/subscription/RG/resource. Additive, inherits downward, least privilege.", d:2},
{c:"What are the Zero Trust principles?", a:"Verify explicitly, use least-privilege access, assume breach", w:"Trust nothing by default — not even inside the network perimeter.", d:2},
{c:"List the defense-in-depth layers.", a:"Physical → identity & access → perimeter → network → compute → application → data", w:"Data sits at the centre as the thing being protected.", d:2},
{c:"What is Microsoft Defender for Cloud?", a:"Continuously assesses security posture and protects workloads against threats", w:"Secure score plus recommendations — across Azure, on-prem, and other clouds.", d:2},

// ---- Domain 3 · management & governance (30–35%) ----
{c:"What factors affect Azure cost?", a:"Resource type & size, region, bandwidth, billing model, licensing", w:"Egress (leaving Azure or crossing regions) is usually billed; ingress is generally free. Azure Hybrid Benefit reuses licences.", d:3},
{c:"What is the Pricing Calculator for?", a:"Estimating the cost of a proposed set of services before you build", w:"Compare configurations and budget.", d:3},
{c:"What is the TCO Calculator for?", a:"Comparing the full cost of on-premises vs Azure", w:"To justify a migration — a different tool and purpose from the Pricing Calculator.", d:3},
{c:"What is Microsoft Cost Management?", a:"Monitor and analyse actual spend, set budgets, trigger cost alerts", w:"Plus recommendations to reduce waste. The 'what am I really spending' tool.", d:3},
{c:"What are tags?", a:"Name/value metadata attached to resources", w:"E.g. Environment=Prod, CostCentre=Finance. Organise resources, group and report costs, drive policy.", d:3},
{c:"What is Microsoft Purview?", a:"Unified data governance and compliance", w:"Discover and catalogue data across Azure, on-prem, other clouds and SaaS; classify sensitive info; map data flows.", d:3},
{c:"What is Azure Policy?", a:"Rules that govern resource configuration, continuously evaluated for compliance", w:"Audit non-compliant resources or deny creation: allowed regions, required tags, approved VM sizes.", d:3},
{c:"What is an initiative?", a:"A group of policies assigned together", w:"Multiple policies bundled into one assignable set.", d:3},
{c:"What are resource locks?", a:"Protection against accidental change or deletion, regardless of a user's permissions", w:"CanNotDelete = read and modify but not delete; ReadOnly = read only. Set at resource, group, or subscription level; inherits downward.", d:3},
{c:"RBAC vs Policy vs lock — one line each.", a:"Who can act · what configuration is permitted · protect this resource even from those with rights", w:"Three controls the exam loves to swap.", d:3},
{c:"What is the Azure portal?", a:"The web-based graphical console for building, managing and monitoring everything", w:"With customisable dashboards.", d:3},
{c:"What is Azure Cloud Shell?", a:"A browser-based shell, authenticated and ready, with no local install", w:"Offers Azure CLI (Bash-style az commands) and Azure PowerShell — pick by scripting preference.", d:3},
{c:"What is Azure Arc?", a:"Projects Azure management and governance outside Azure", w:"Manage on-prem servers, other clouds' VMs, and Kubernetes clusters as Azure resources, with consistent Policy and RBAC.", d:3},
{c:"What is Infrastructure as Code?", a:"Describing infrastructure in declarative configuration files", w:"You state the desired end-state; deployments become repeatable, consistent, version-controlled.", d:3},
{c:"What is Azure Resource Manager?", a:"The deployment and management layer that executes every resource request", w:"From portal, CLI, PowerShell or SDKs — handling auth, ordering, and consistency.", d:3},
{c:"ARM templates vs Bicep?", a:"JSON templates vs a simpler language that compiles to ARM", w:"Both declare resources for repeatable IaC deployments.", d:3},
{c:"What is Azure Advisor?", a:"Personalised recommendations from your usage and configuration", w:"Five pillars: cost, security, reliability, operational excellence, performance.", d:3},
{c:"What is Azure Service Health?", a:"The health of Azure itself as it affects you", w:"Service outages, planned maintenance, and advisories for the regions and services you use.", d:3},
{c:"What are the related health views?", a:"The global Azure status page, and Resource Health for individual resources", w:"Azure-wide vs your specific resource.", d:3},
{c:"What is Azure Monitor?", a:"The platform that collects, analyses, and acts on telemetry", w:"Metrics and logs from across your environment.", d:3},
{c:"What is Log Analytics?", a:"Store and query log data using KQL", w:"A key Azure Monitor component.", d:3},
{c:"What are Azure Monitor alerts?", a:"Notifications or automated actions fired when a condition is met", w:"Part of Azure Monitor.", d:3},
{c:"What is Application Insights?", a:"Monitors the performance and usage of your applications", w:"Part of Azure Monitor.", d:3},
{c:"Advisor vs Service Health vs Monitor — one line each.", a:"Recommendations for your setup · is Azure itself broken · collect and query your own telemetry", w:"Three monitoring tools, three jobs.", d:3},
{c:"What does 700/1000 mean, and what should you verify at booking?", a:"A scaled score, not 70% correct — verify cost, timing and question count when you book", w:"Pass score and domains are confirmed by Microsoft; logistics are third-party figures.", d:3}
],

examBank: [
// ---- Domain 1 ----
{q:"A retailer must keep its customer database on-premises for compliance, but wants its web tier to scale into the cloud during holiday peaks. Which deployment model fits?", opts:["Public cloud","Private cloud","Hybrid cloud","A sovereign region"], c:2, w:"Hybrid combines public and private, connected so workloads can move between them — sensitive stays private, scale bursts to public.", d:1},
{q:"In EVERY service model — on-prem, IaaS, PaaS, SaaS — which responsibility is always the customer's?", opts:["Patching the operating system","Data, identities, and access management","The physical network","Virtualisation"], c:1, w:"The top layer never transfers: your data, accounts and access (plus endpoint devices) are always yours.", d:1},
{q:"In PaaS, who manages the operating system and runtime?", opts:["The customer","Microsoft","Shared between both","It depends on the region"], c:1, w:"In PaaS you manage only your apps and data; Microsoft owns OS, runtime, scaling, hosting, hardware.", d:1},
{q:"Moving from buying servers up front to a metered monthly bill is best described as…", opts:["OpEx becoming CapEx","CapEx becoming OpEx via the consumption model","Reserved capacity","Vertical scaling"], c:1, w:"The consumption-based model turns capital expenditure into operational expenditure.", d:1},
{q:"A workload runs steadily 24/7 and will do so for the next three years. Which pricing model minimises its cost?", opts:["Pay-as-you-go","Spot","Reserved instances","Serverless"], c:2, w:"Reserved = commit 1 or 3 years for a large discount — built for steady workloads.", d:1},
{q:"A batch job can be interrupted and restarted at any time, and you want the lowest possible price. Choose:", opts:["Spot","Reserved instances","Pay-as-you-go","A dedicated host"], c:0, w:"Spot is heavily discounted spare capacity that Azure can reclaim at any time — for interruptible work.", d:1},
{q:"Which statement about 'serverless' is accurate?", opts:["No servers are involved anywhere","You manage the servers but Microsoft owns them","You supply code; the platform provisions and scales, and you pay per execution","It is only available for containers"], c:2, w:"Serverless means you don't manage the servers — not that they don't exist.", d:1},
{q:"Adding five more identical VM instances behind a load balancer is called…", opts:["Scaling up","Scaling out (horizontal)","Vertical scaling","Failover"], c:1, w:"Horizontal = add/remove instances; vertical = a bigger/smaller machine.", d:1},
{q:"A system keeps consistent response times under load AND its bill is easy to forecast. Which benefit is this?", opts:["Reliability","Elasticity","Predictability","High availability"], c:2, w:"Predictability has two flavours the exam separates: performance and cost. Reliability is recovery from failure.", d:1},
{q:"The ability to recover from failures and continue to function is…", opts:["Predictability","Reliability","Scalability","Manageability"], c:1, w:"Reliability = fault tolerance and disaster recovery. Routinely offered as a distractor for predictability.", d:1},
{q:"Resources are added and removed automatically as demand rises and falls. This is…", opts:["Scalability","Elasticity","High availability","Agility"], c:1, w:"Scalability is the capability; elasticity is doing it dynamically.", d:1},
{q:"An availability SLA expresses…", opts:["The number of regions used","A percentage of uptime the provider commits to","Your monthly spend limit","The number of redundant copies"], c:1, w:"HA is expressed as an availability SLA.", d:1},
{q:"Which model gives maximum control and isolation, but you bear the hardware cost and its scale limits?", opts:["Public cloud","Hybrid cloud","Private cloud","SaaS"], c:2, w:"Private cloud: dedicated to one organisation, on-prem or hosted.", d:1},
{q:"Using the portal, CLI, PowerShell, or APIs to administer resources is an example of…", opts:["Management OF the cloud","Management IN the cloud","Infrastructure as Code","Governance"], c:1, w:"IN = how you administer. OF = the cloud managing resources for you (autoscale, templates, monitoring).", d:1},
{q:"'The team just needs working email and CRM, ready to use, nothing to build.' Which service type?", opts:["IaaS","PaaS","SaaS","Serverless"], c:2, w:"SaaS = ready-to-use software (Microsoft 365, Dynamics 365); you manage data and user access only.", d:1},

// ---- Domain 2 ----
{q:"Three or more physically separate locations within a single region, each with independent power, cooling, and networking:", opts:["Region pairs","Availability zones","Availability sets","Fault domains"], c:1, w:"Availability zones protect against a single datacentre failing.", d:2},
{q:"You need VMs protected from a rack failure and from being rebooted simultaneously during maintenance — within ONE datacentre. Use:", opts:["An availability set","Availability zones","A region pair","VM Scale Sets"], c:0, w:"Availability sets spread VMs across fault domains and update domains. They do not survive whole-datacentre loss.", d:2},
{q:"Which statement about region pairs is TRUE?", opts:["Every Azure region has a pair","Being paired automatically fails your resources over","Not every region has a pair; many newer regions rely on availability zones instead","Pairs are always in different geographies"], c:2, w:"And pairing alone gives no HA/failover/DR — you design that yourself (e.g. GRS).", d:2},
{q:"You delete a resource group. What happens to the resources inside it?", opts:["They move to the subscription's default group","They are all deleted","They are locked","Nothing until you delete them individually"], c:1, w:"Deleting the group deletes everything in it.", d:2},
{q:"Which is TRUE of resource groups?", opts:["They can be nested","A resource can belong to several groups","They can contain resources from different regions","All resources must match the group's region"], c:2, w:"The group's region only stores metadata. No nesting; a resource lives in exactly one group.", d:2},
{q:"You must apply one policy across 40 subscriptions with minimal effort. Assign it at…", opts:["Each resource group","Each subscription","A management group above them","The Azure portal dashboard"], c:2, w:"Management groups sit above subscriptions; RBAC and Policy applied there inherit to everything beneath.", d:2},
{q:"Order the hierarchy from top to bottom:", opts:["Subscription → management group → resource → resource group","Management group → subscription → resource group → resource","Resource group → subscription → management group → resource","Tenant → resource group → subscription → resource"], c:1, w:"Policy and role assignments inherit downward, never up.", d:2},
{q:"A subscription is a boundary for…", opts:["Only billing","Billing, access, and resource limits/quotas","Only identity","Only networking"], c:1, w:"It's the logical unit of billing AND a boundary for access and quotas.", d:2},
{q:"Which VM family fits SAP HANA or a huge in-memory database?", opts:["F-series","L-series","M-series","B-series"], c:2, w:"Memory optimised; M = ultra-high memory.", d:2},
{q:"CPU-bound batch processing should run on…", opts:["Compute optimised (F)","Memory optimised (E)","GPU (N)","General purpose (B)"], c:0, w:"F = high CPU-to-memory: batch, app servers, network appliances, gaming.", d:2},
{q:"A large NoSQL database needs very high local disk throughput and IOPS. Pick the family:", opts:["H-series","L-series (storage optimised)","D-series","NV-series"], c:1, w:"L = lots of local disk throughput: big data, warehousing, large transactional/NoSQL DBs.", d:2},
{q:"Training machine-learning models calls for…", opts:["B-series","F-series","N-series (GPU)","L-series"], c:2, w:"N = GPU: AI/ML training and inference, rendering, visualisation.", d:2},
{q:"A cheap dev/test box that only occasionally bursts to full CPU:", opts:["M-series","B-series (burstable)","HX-series","NC-series"], c:1, w:"B = burstable/economical, within general purpose.", d:2},
{q:"The key architectural difference between containers and VMs is that containers…", opts:["Each carry a full guest OS","Share the host's OS kernel","Provide stronger isolation than VMs","Can only run Linux"], c:1, w:"A VM virtualises hardware; a container virtualises the OS — smaller, faster to start, denser.", d:2},
{q:"A container image is best described as…", opts:["A running instance","An immutable template that containers are started from","A Dockerfile","A registry"], c:1, w:"Dockerfile builds the image; a running instance of the image is a container. Class vs object.", d:2},
{q:"Where do you store and share private container images on Azure?", opts:["Azure Blob Storage","Azure Container Registry","Azure Files","AKS"], c:1, w:"ACR is the registry.", d:2},
{q:"You need to run ONE container for a short task — no orchestration, billed per second. Use:", opts:["AKS","Azure Container Instances","VM Scale Sets","Azure Virtual Desktop"], c:1, w:"ACI: serverless, quick, for simple/short/burst tasks.", d:2},
{q:"Dozens of microservice containers need automatic scheduling, self-healing, and rolling updates. Use:", opts:["ACI","Azure Functions","Azure Kubernetes Service","Azure Files"], c:2, w:"AKS orchestrates many containers; Azure manages the control plane, you manage worker nodes.", d:2},
{q:"You want serverless containers with autoscaling, but nobody on the team should manage Kubernetes. Use:", opts:["Azure Container Apps","AKS","A VM with Docker","App Service"], c:0, w:"Container Apps is the middle ground between ACI and AKS.", d:2},
{q:"How many triggers can a single Azure Function have?", opts:["None — triggers are optional","Exactly one","Up to three","Unlimited"], c:1, w:"Every function has one and only one trigger; bindings are the optional, multiple part.", d:2},
{q:"A function must write its result to a storage queue without any connection-handling code. Use…", opts:["A second trigger","An output binding","A Logic App","Durable Functions"], c:1, w:"Bindings connect declaratively; input brings data in, output sends it out.", d:2},
{q:"A Consumption-plan function responds slowly to the first request after sitting idle. The cause, and the fix?", opts:["Throttling — add CPU","Cold start — move to Premium/Flex with pre-warmed instances","A missing binding — add one","Network latency — use ExpressRoute"], c:1, w:"Cold start is the delay when a Consumption-plan function spins up after idle.", d:2},
{q:"Every Function App requires an associated…", opts:["Storage account","AKS cluster","Public IP","ExpressRoute circuit"], c:0, w:"Used for managing triggers, logging, and scaling state.", d:2},
{q:"A cleanup job must run every night at 2am. Which trigger?", opts:["HTTP","Blob","Timer","Cosmos DB"], c:2, w:"Timer = run on a schedule.", d:2},
{q:"Connect your entire on-premises network to Azure with an encrypted tunnel over the internet:", opts:["Point-to-site VPN","Site-to-site VPN","VNet peering","Azure DNS"], c:1, w:"Site-to-site connects whole networks; point-to-site connects individual client devices.", d:2},
{q:"Traffic between your datacentre and Azure must never traverse the public internet and needs consistent performance. Choose:", opts:["Site-to-site VPN","ExpressRoute","Global VNet peering","A public endpoint"], c:1, w:"ExpressRoute is private and dedicated, via a connectivity provider — faster, more consistent, more secure, higher cost.", d:2},
{q:"Two VNets in different regions must communicate privately over Microsoft's backbone. Use:", opts:["Global VNet peering","A public load balancer","Azure DNS","Point-to-site VPN"], c:0, w:"Peering can be within a region or global across regions.", d:2},
{q:"A PaaS service must be reachable only via a private IP inside your VNet. Configure…", opts:["A public endpoint","A private endpoint","An availability zone","A service tag"], c:1, w:"Private endpoints keep traffic on the private network and off the internet.", d:2},
{q:"Store video files, backups, and logs at massive scale, accessed over HTTPS:", opts:["Azure Files","Blob Storage","Table Storage","Disk Storage"], c:1, w:"Blob = object storage for unstructured data.", d:2},
{q:"A lifted-and-shifted app needs an SMB file share mounted by both cloud VMs and on-prem machines:", opts:["Blob Storage","Queue Storage","Azure Files","Table Storage"], c:2, w:"Azure Files: managed SMB/NFS shares, mountable from both simultaneously.", d:2},
{q:"Decouple a front-end from a back-end by passing messages between them:", opts:["Queue Storage","Disk Storage","Azure DNS","Blob Storage"], c:0, w:"Queues store large numbers of messages and smooth out spikes.", d:2},
{q:"Compliance data is touched about once a year, retrieval latency of hours is fine, and storage must be as cheap as possible:", opts:["Hot","Cool","Cold","Archive"], c:3, w:"Archive is offline and cheapest to store — but must be rehydrated before reading, and retrieval costs the most.", d:2},
{q:"Data is rarely read but MUST be instantly readable when needed, and will be kept at least 90 days:", opts:["Archive","Cold","Hot","LRS"], c:1, w:"Cold = rarely accessed, min ~90 days, still online. Archive would require rehydration.", d:2},
{q:"Storage must survive a full REGION outage, and the app must READ from the secondary during it:", opts:["ZRS","GRS","RA-GRS","LRS"], c:2, w:"GRS/GZRS survive region loss; only the RA- variants add read access to the secondary.", d:2},
{q:"Storage must survive the loss of one datacentre, staying within a single region:", opts:["LRS","ZRS","GRS","RA-GZRS"], c:1, w:"ZRS spreads copies across availability zones in one region.", d:2},
{q:"Keep an on-prem Windows file server as a fast local cache of shares that live in Azure:", opts:["AzCopy","Azure File Sync","Storage Explorer","Data Box"], c:1, w:"File Sync keeps on-prem servers in sync with Azure Files, caching hot data locally.", d:2},
{q:"You must move 400 TB to Azure and your internet link makes network transfer unrealistic:", opts:["AzCopy","Azure Data Box","Blob Cool tier","VNet peering"], c:1, w:"Data Box is the ruggedised physical appliance for very large offline transfers.", d:2},
{q:"Before migrating, you need to discover and assess your on-prem servers centrally:", opts:["Azure Migrate","Azure Monitor","Azure Arc","Azure Advisor"], c:0, w:"Migrate is the discover/assess/migrate hub.", d:2},
{q:"Which combination satisfies MFA?", opts:["Password + security questions","Password + code from an authenticator app","Two different passwords","Username + password"], c:1, w:"MFA needs two DIFFERENT categories: know / have / are. Two 'know' factors don't count.", d:2},
{q:"Require MFA only when a sign-in comes from outside the corporate network. Configure…", opts:["Azure Policy","Conditional Access","A resource lock","RBAC"], c:1, w:"Conditional Access evaluates signals (location, device, risk) and can require extra proof.", d:2},
{q:"Give a support team read-only access to everything in one resource group:", opts:["Assign the Reader role at the resource group scope","Apply a ReadOnly lock","Create a policy initiative","Add them to the subscription as Owners"], c:0, w:"RBAC answers 'who can do what' — Reader at RG scope, least privilege.", d:2},
{q:"A legacy app needs domain join and Group Policy, but you refuse to run domain controllers. Use:", opts:["Microsoft Entra ID alone","Microsoft Entra Domain Services","Conditional Access","Azure Arc"], c:1, w:"Entra Domain Services provides managed domain join, GPO, LDAP, Kerberos/NTLM.", d:2},
{q:"A partner organisation's users should access your app with their OWN credentials. That is…", opts:["B2C","B2B","SSO","Passwordless"], c:1, w:"B2B invites partners/guests; B2C is for customer-facing apps.", d:2},
{q:"Which set is the Zero Trust principles?", opts:["Trust but verify; defense in depth; encryption","Verify explicitly; least privilege; assume breach","Perimeter first; segment later; monitor always","Authenticate once; authorise everywhere"], c:1, w:"Zero Trust assumes breach and trusts nothing by default.", d:2},
{q:"In the defense-in-depth model, which layer sits at the centre?", opts:["Network","Identity & access","Data","Perimeter"], c:2, w:"Data is the thing being protected; the layers wrap around it.", d:2},
{q:"Continuous security posture assessment with a secure score, across Azure, on-prem and other clouds:", opts:["Microsoft Purview","Microsoft Defender for Cloud","Azure Monitor","Microsoft Entra ID"], c:1, w:"Defender for Cloud assesses posture and protects workloads.", d:2},

// ---- Domain 3 ----
{q:"Estimate the monthly cost of an architecture you have NOT yet deployed:", opts:["TCO Calculator","Microsoft Cost Management","Pricing Calculator","Azure Advisor"], c:2, w:"Pricing Calculator = estimate a future build. Three cost tools, three jobs.", d:3},
{q:"Build the business case comparing your datacentre's full running cost against Azure:", opts:["Pricing Calculator","TCO Calculator","Cost Management","Azure Monitor"], c:1, w:"TCO = on-prem vs cloud comparison, to justify migration.", d:3},
{q:"Get alerted when a subscription's spend passes a monthly budget:", opts:["Azure Service Health","Microsoft Cost Management","Pricing Calculator","Resource locks"], c:1, w:"Cost Management tracks actual spend, sets budgets, and fires cost alerts.", d:3},
{q:"Which network traffic is usually billed?", opts:["Ingress into Azure","Egress leaving Azure or crossing regions","All traffic equally","None — bandwidth is free"], c:1, w:"Egress is usually billed; ingress is generally free.", d:3},
{q:"Force every new resource to carry a CostCentre tag, blocking creation without it:", opts:["RBAC","Azure Policy","A resource lock","Tags applied manually"], c:1, w:"Policy governs configuration and can deny non-compliant creation.", d:3},
{q:"A group of policies assigned together is called…", opts:["A blueprint","An initiative","A management group","A compliance pack"], c:1, w:"Multiple policies grouped into an initiative.", d:3},
{q:"Nobody — not even Owners — should be able to delete the production database by accident. Apply:", opts:["A CanNotDelete lock","The Reader role","An Azure Policy audit","A ReadOnly lock"], c:0, w:"Locks work regardless of a user's permissions. CanNotDelete still allows read and modify.", d:3},
{q:"What does a ReadOnly lock allow?", opts:["Read and modify, but not delete","Read only — no changes and no deletion","Delete only","Nothing at all"], c:1, w:"ReadOnly is stricter than CanNotDelete.", d:3},
{q:"Discover, catalogue and classify sensitive data across Azure, on-prem, other clouds and SaaS:", opts:["Microsoft Purview","Azure Monitor","Defender for Cloud","Log Analytics"], c:0, w:"Purview = unified data governance and compliance.", d:3},
{q:"Govern VMs running in AWS and on-prem with the SAME Azure Policy and RBAC you use in Azure:", opts:["Azure Migrate","Azure Arc","ExpressRoute","Azure Virtual Desktop"], c:1, w:"Arc projects Azure management outside Azure.", d:3},
{q:"A simpler declarative language that compiles down to ARM templates:", opts:["KQL","Bicep","YAML","PowerShell DSC"], c:1, w:"Bicep compiles to ARM (JSON) — both are IaC.", d:3},
{q:"Every request to create, update or delete a resource — from portal, CLI, PowerShell or SDK — passes through:", opts:["Azure Monitor","Azure Resource Manager","Cloud Shell","The subscription"], c:1, w:"ARM is the deployment and management layer handling auth, ordering, consistency.", d:3},
{q:"A browser-based, pre-authenticated shell offering both Azure CLI and Azure PowerShell:", opts:["Azure Cloud Shell","Windows Terminal","Bastion","Azure Arc"], c:0, w:"No local install required; pick CLI or PowerShell by preference.", d:3},
{q:"Personalised recommendations across cost, security, reliability, operational excellence and performance:", opts:["Azure Service Health","Azure Advisor","Microsoft Cost Management","Application Insights"], c:1, w:"Advisor's five pillars — the 'how do I improve my environment' tool.", d:3},
{q:"You suspect a regional Azure outage is affecting your services. Check first:", opts:["Azure Advisor","Azure Service Health","Log Analytics","The Pricing Calculator"], c:1, w:"Service Health covers Azure's own outages, maintenance and advisories for YOUR regions and services.", d:3},
{q:"Query your application's log data using KQL:", opts:["Log Analytics (Azure Monitor)","Azure Advisor","Microsoft Purview","Azure Policy"], c:0, w:"Log Analytics stores and queries logs with KQL.", d:3},
{q:"Monitor a web application's performance and usage:", opts:["Service Health","Application Insights","Cost Management","Resource Health"], c:1, w:"Application Insights is Azure Monitor's app-performance component.", d:3},
{q:"You scored 700/1000 on AZ-900. That means…", opts:["Exactly 70% of questions correct","A scaled passing score — not a raw percentage","You failed by 300 points","Each domain scored 700"], c:1, w:"700/1000 is scaled, confirmed by Microsoft. Question count, timing and cost vary — verify at booking.", d:3}
],

scenarios: [
{q:"A legacy accounting app needs full control of the operating system, including custom kernel settings.", opts:["App Service","Virtual Machines","Azure Functions","Container Apps"], c:1, w:"Full OS control = IaaS = a VM. You own patching from the OS up.", d:2},
{q:"Deploy a web app where nobody on the team ever touches a server.", opts:["App Service","Virtual Machines","AKS","Azure Virtual Desktop"], c:0, w:"App Service is PaaS: you manage only your app and data.", d:2},
{q:"Generate a thumbnail automatically every time an image lands in storage, paying only per run.", opts:["A VM with a cron job","App Service","Azure Functions (Blob trigger)","Azure Files"], c:2, w:"Event-driven code, pay per execution — Functions with a Blob trigger.", d:2},
{q:"Run identical web VMs whose instance count grows and shrinks with traffic, behind a load balancer.", opts:["Availability sets","VM Scale Sets","ACI","Region pairs"], c:1, w:"Scale Sets are how IaaS VMs achieve elasticity.", d:2},
{q:"Sixty microservice containers need scheduling, self-healing and rolling updates.", opts:["ACI","Azure Kubernetes Service","One big VM","Queue Storage"], c:1, w:"Many containers with orchestration = AKS.", d:2},
{q:"Run one container for a ten-minute data-crunch task, billed per second, no cluster.", opts:["Azure Container Instances","AKS","VM Scale Sets","App Service"], c:0, w:"ACI: single/simple/short container work without orchestration.", d:2},
{q:"Autoscaling containerised microservices, but the team must never manage Kubernetes.", opts:["AKS","A Docker VM","Azure Container Apps","Azure Arc"], c:2, w:"Container Apps: serverless containers, autoscaling, no K8s admin.", d:2},
{q:"Give offshore contractors managed Windows desktops they can reach from their own devices.", opts:["Azure Virtual Desktop","B2C","Point-to-site VPN","Entra Domain Services"], c:0, w:"AVD delivers virtualised Windows desktops from Azure.", d:2},
{q:"The finance feed between your datacentre and Azure must never touch the public internet.", opts:["Site-to-site VPN","ExpressRoute","Global VNet peering","A private endpoint"], c:1, w:"ExpressRoute is the private, dedicated connection via a provider.", d:2},
{q:"Connect the head-office network to Azure cheaply; encrypted traffic over the internet is acceptable.", opts:["ExpressRoute","Point-to-site VPN","Site-to-site VPN","Azure DNS"], c:2, w:"S2S VPN: whole network, encrypted tunnel, lower cost.", d:2},
{q:"One consultant's laptop needs a secure tunnel into the Azure VNet while travelling.", opts:["Site-to-site VPN","ExpressRoute","VNet peering","Point-to-site VPN"], c:3, w:"P2S connects individual client devices.", d:2},
{q:"Two VNets in different regions must talk privately without leaving Microsoft's backbone.", opts:["Global VNet peering","Public IPs on both","A site-to-site VPN","Service Health"], c:0, w:"Peering routes privately; global peering spans regions.", d:2},
{q:"Host and resolve your company's DNS zone using Azure infrastructure.", opts:["Azure DNS","VNet peering","Azure Files","Traffic on port 53 to a VM"], c:0, w:"Azure DNS hosts your domains on Microsoft's resolution infrastructure.", d:2},
{q:"Store millions of product photos, videos and log files, served over HTTPS.", opts:["Table Storage","Disk Storage","Blob Storage","Queue Storage"], c:2, w:"Unstructured objects at massive scale = Blob.", d:2},
{q:"A lifted app expects an SMB share reachable from cloud VMs AND the on-prem office.", opts:["Blob Storage","Azure Files","Queue Storage","Archive tier"], c:1, w:"Azure Files: managed SMB/NFS shares, mountable from both at once.", d:2},
{q:"Let the order front-end hand work to the back-end without the two being coupled.", opts:["Queue Storage","Disk Storage","Azure DNS","ExpressRoute"], c:0, w:"Queues pass messages between components and absorb spikes.", d:2},
{q:"Store billions of structured but non-relational key/value records as cheaply as possible.", opts:["Azure SQL","Table Storage","Blob Archive","Azure Files"], c:1, w:"Table Storage: NoSQL key/value at scale.", d:2},
{q:"Attach fast persistent block storage to a database VM.", opts:["Blob Storage","Queue Storage","Disk Storage (Premium SSD)","Azure Files"], c:2, w:"Disks are the block-level storage for VMs.", d:2},
{q:"Seven-year compliance archives, read perhaps once a year; hours of retrieval delay is fine.", opts:["Hot tier","Cool tier","Cold tier","Archive tier"], c:3, w:"Archive: cheapest to store, offline, rehydrate before reading.", d:2},
{q:"Storage must survive a whole-region outage AND stay readable from the secondary during it.", opts:["LRS","ZRS","RA-GRS","GRS"], c:2, w:"Only the RA- variants add read access to the paired-region copy.", d:2},
{q:"Script a fast bulk upload of 2 TB of files into Blob Storage from the command line.", opts:["AzCopy","Storage Explorer","Data Box","OneDrive sync"], c:0, w:"AzCopy is the CLI bulk-transfer tool.", d:2},
{q:"An admin wants to browse containers and tweak blobs with a point-and-click desktop app.", opts:["AzCopy","Cloud Shell","Azure Storage Explorer","KQL"], c:2, w:"Storage Explorer is the GUI.", d:2},
{q:"Branch offices should keep a local cache of file shares whose master copy lives in Azure Files.", opts:["Azure File Sync","Data Box","AzCopy","Blob Cool tier"], c:0, w:"File Sync keeps on-prem Windows servers synced, caching hot data locally.", d:2},
{q:"Move 500 TB of archives to Azure over a link that would take a year to upload.", opts:["AzCopy overnight","Azure Data Box","ExpressRoute","RA-GZRS"], c:1, w:"Data Box: Microsoft ships you a physical appliance for offline transfer.", d:2},
{q:"A legacy app being lifted to Azure still needs domain join and Group Policy — with no domain controllers to run.", opts:["Microsoft Entra ID alone","Conditional Access","Microsoft Entra Domain Services","Azure Arc"], c:2, w:"Entra Domain Services: managed domain join, GPO, LDAP, Kerberos.", d:2},
{q:"Require MFA only when sign-ins come from outside the office network.", opts:["Conditional Access","A ReadOnly lock","Azure Policy","RBAC"], c:0, w:"Conditional Access evaluates location/device/risk signals and demands extra proof.", d:2},
{q:"Estimate what a planned three-VM architecture will cost before anything is deployed.", opts:["Cost Management","TCO Calculator","Pricing Calculator","Azure Advisor"], c:2, w:"Pricing Calculator = estimate a future build.", d:3},
{q:"Build the board's business case: current datacentre cost versus running the same estate in Azure.", opts:["Pricing Calculator","TCO Calculator","Budgets","Purview"], c:1, w:"TCO Calculator compares on-prem vs Azure.", d:3},
{q:"Finance wants an alert the moment the subscription passes $5,000 in a month.", opts:["Microsoft Cost Management","Service Health","Azure Monitor metrics","Advisor"], c:0, w:"Cost Management: actual spend, budgets, cost alerts.", d:3},
{q:"Stop anyone — Owners included — accidentally deleting the production resource group.", opts:["Remove Owner roles","A CanNotDelete lock","An Azure Policy audit","Tags"], c:1, w:"Locks apply regardless of RBAC permissions.", d:3},
{q:"Ensure every future resource is created only in Australia East, blocking anything else.", opts:["RBAC","Resource locks","Azure Policy (allowed locations)","A management group"], c:2, w:"Policy governs allowed configuration and can deny creation.", d:3},
{q:"Get tailored suggestions to cut cost and tighten security across the subscription.", opts:["Azure Advisor","Service Health","Log Analytics","Pricing Calculator"], c:0, w:"Advisor: recommendations across five pillars.", d:3},
{q:"Users report errors; you need to know within minutes whether Azure itself is having a regional incident.", opts:["Azure Advisor","Azure Service Health","Cost Management","Purview"], c:1, w:"Service Health: Azure's own outages, maintenance and advisories for your services.", d:3},
{q:"Trace a spike in app errors by querying the collected logs with KQL.", opts:["Log Analytics","Service Health","Azure Arc","Storage Explorer"], c:0, w:"Log Analytics stores and queries logs — Azure Monitor's query engine.", d:3},
{q:"Apply your Azure Policy and RBAC model to VMs still running in AWS and on-prem.", opts:["Azure Migrate","ExpressRoute","Azure Arc","Entra Domain Services"], c:2, w:"Arc projects Azure governance outside Azure.", d:3}
],

matchPairs: [
{c:"Recover from failure", a:"Reliability", d:1},
{c:"Forecastable bill", a:"Predictability", d:1},
{c:"Auto scale with demand", a:"Elasticity", d:1},
{c:"Bigger machine", a:"Scale up (vertical)", d:1},
{c:"More machines", a:"Scale out (horizontal)", d:1},
{c:"Buy servers upfront", a:"CapEx", d:1},
{c:"Metered monthly cost", a:"OpEx", d:1},
{c:"1 or 3-year discount", a:"Reserved instances", d:1},
{c:"Reclaimable cheap capacity", a:"Spot", d:1},
{c:"On-prem + cloud burst", a:"Hybrid cloud", d:1},
{c:"Ready-to-use software", a:"SaaS", d:1},
{c:"Full OS control", a:"IaaS", d:1},
{c:"Your app + data only", a:"PaaS", d:1},
{c:"Survive one datacentre", a:"Availability zones", d:2},
{c:"Racks + staggered reboots", a:"Availability set", d:2},
{c:"Survive a region loss", a:"GRS / GZRS", d:2},
{c:"Read the secondary copy", a:"RA-GRS", d:2},
{c:"~300 miles apart", a:"Region pair", d:2},
{c:"Billing + access boundary", a:"Subscription", d:2},
{c:"Sits above subscriptions", a:"Management group", d:2},
{c:"Identical VMs, autoscaling", a:"VM Scale Sets", d:2},
{c:"Cloud Windows desktops", a:"Azure Virtual Desktop", d:2},
{c:"SAP HANA, huge memory", a:"M-series", d:2},
{c:"GPU / ML training", a:"N-series", d:2},
{c:"One quick container", a:"ACI", d:2},
{c:"Orchestrate many containers", a:"AKS", d:2},
{c:"Serverless, no K8s admin", a:"Container Apps", d:2},
{c:"Makes a Function run", a:"Trigger", d:2},
{c:"Data in/out, no plumbing", a:"Bindings", d:2},
{c:"Private dedicated link", a:"ExpressRoute", d:2},
{c:"Encrypted over internet", a:"VPN Gateway", d:2},
{c:"Unstructured objects", a:"Blob Storage", d:2},
{c:"SMB / NFS file shares", a:"Azure Files", d:2},
{c:"Decoupling messages", a:"Queue Storage", d:2},
{c:"Offline, hours to read", a:"Archive tier", d:2},
{c:"Proving who you are", a:"Authentication", d:2},
{c:"What you're allowed", a:"Authorization", d:2},
{c:"Verify · least priv · breach", a:"Zero Trust", d:2},
{c:"Estimate a future build", a:"Pricing Calculator", d:3},
{c:"On-prem vs Azure cost", a:"TCO Calculator", d:3},
{c:"Budgets + spend alerts", a:"Cost Management", d:3},
{c:"Who can do what", a:"RBAC", d:3},
{c:"Allowed configuration", a:"Azure Policy", d:3},
{c:"Block deletion outright", a:"Resource lock", d:3},
{c:"Five-pillar recommendations", a:"Azure Advisor", d:3},
{c:"Is Azure itself down?", a:"Service Health", d:3},
{c:"Query logs with KQL", a:"Log Analytics", d:3},
{c:"Manage beyond Azure", a:"Azure Arc", d:3}
]

};
